/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class clz_Register */

#ifndef _Included_clz_Register
#define _Included_clz_Register
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     clz_Register
 * Method:    helloworld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_clz_Register_helloworld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
